name: 'Build Test'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2 
    with: 
      node-version: '14.16.0' 
      cache: 'yarn'

  - shell: bash
    run: |
      yarn install --frozen-lockfile
      yarn test || true
      yarn lint || true
      yarn build
