// This file was generated by script
export { default as arrow } from './arrow.svg';
export { default as burger } from './burger.svg';
export { default as close } from './close.svg';
export { default as crown } from './crown.svg';
export { default as dropdownArrow } from './dropdownArrow.svg';
export { default as gitHub } from './gitHub.svg';
export { default as magicPoweredLogo } from './magicPoweredLogo.svg';
export { default as near } from './near.svg';
export { default as nearRound } from './nearRound.svg';
export { default as search } from './search.svg';
export { default as stats } from './stats.svg';
