// This file was generated by script
export { default as arrow } from './arrow.svg';
export { default as crown } from './crown.svg';
export { default as near } from './near.svg';
export { default as search } from './search.svg';
export { default as stats } from './stats.svg';
