apiVersion: v1
kind: ConfigMap
metadata:
  name: dao-stats-ui-configmap
data:
  PORT: '3000'
  NODE_ENV: 'production'
  REACT_APP_MAINNET: '{{ .Values.environment.react_app_mainnet }}'
  REACT_APP_TESTNET: '{{ .Values.environment.react_app_testnet }}'
  REACT_APP_API_ENDPOINT: '{{ .Values.environment.react_app_api_endpoint }}'
