name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
    - '**'
    paths:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
         cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV

    - name: Build Test
      uses: ./.github/actions/build-test
